### ISSUE TITLE
does it work for Mac osx? I don't see a .dms file to execute?

### ISSUE THREAD

**Issue by mnbv-prog** [Sorrow446/Qo-DL-Reborn#3]
thanks for any advice. I used the previous version but I am a bit lost with this..

**Comment by Sorrow446** [comment]
It does. I only compile for Windows, sorry. You'll need to install to install Python and all requirements listed in "requirements.txt". It's pretty simple. 

1. Download Qo-DL Reborn repo as zip and unpack it (https://github.com/Sorrow446/Qo-DL-Reborn/archive/master.zip).
2. Install Python v3.6.7 (https://www.python.org/ftp/python/3.6.7/python-3.6.7-macosx10.6.pkg)
Reborn was written in v3.6.7, so it'd work best on this version. 
3. Launch terminal and cd to unpacked repo dir. `cd C:\Users\Sorrow\Downloads\Qo-DL-Reborn-master`
4. Install reqs. pip3 `install -r requirements.txt`
5. Launch Reborn. `python 3 qo-dl_reborn.py`

You'll need to cd into Reborn's dir every time you launch it so that it can read its config file.

**Comment by mnbv-prog** [comment]
thanks. step 4  "install -r requirements.txt" doesn't seem to work
I get this: 
install: illegal option -- r
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...

**Comment by Sorrow446** [comment]
`pip3 install -r requirements.txt`

**Comment by mnbv-prog** [comment]
solved thanks!

**Comment by Bradsr12** [comment]
May I ask if you managed to get this installed on Mac? 
Mine just say “no such file or directory” 
Many thanks
